import { ImageSourcePropType } from 'react-native';
import { CategoryKey, CATEGORIES, CATEGORY_LIST } from './categories';

export type MarkerStyle = 'teardrop' | 'classic';

/**
 * Teardrop markers (generated by scripts/gen-markers.mjs) — category-colored
 * pin + white circle + monoline icon, matching the "Clean Berlin" design.
 * The `classic` set reuses the illustrated PNGs declared on each category.
 */
const TEARDROP: Record<CategoryKey, ImageSourcePropType> = {
  drinking: require('../../assets/markers/teardrop_drinking.png'),
  toilet: require('../../assets/markers/teardrop_toilet.png'),
  bbq: require('../../assets/markers/teardrop_bbq.png'),
  bikeRepair: require('../../assets/markers/teardrop_bikeRepair.png'),
  evCharging: require('../../assets/markers/teardrop_evCharging.png'),
  playground: require('../../assets/markers/teardrop_playground.png'),
  bathing: require('../../assets/markers/teardrop_bathing.png'),
  coolSpace: require('../../assets/markers/teardrop_coolSpace.png'),
  decorative: require('../../assets/markers/teardrop_decorative.png'),
};

/** On-screen icon size passed to the MapLibre SymbolLayer, per marker style. */
export const MARKER_ICON_SIZE: Record<MarkerStyle, number> = {
  teardrop: 0.34,
  classic: 0.22,
};

/** Marker image for a category under the given style. */
export function markerImageFor(style: MarkerStyle, key: CategoryKey): ImageSourcePropType {
  return style === 'teardrop' ? TEARDROP[key] : CATEGORIES[key].markerIcon;
}

/** Record of { imageKey → source } for all categories under the given style. */
export function markerImages(style: MarkerStyle): Record<string, ImageSourcePropType> {
  const images: Record<string, ImageSourcePropType> = {};
  for (const cat of CATEGORY_LIST) {
    images[cat.markerImageKey] = markerImageFor(style, cat.key);
  }
  return images;
}
